### PR TITLE
feat: expose FromSchema options

### PR DESCRIPTION
**Pull request by kalvenschraut**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

There are not a lot of tests/documentation for this package  or any benchmarks so not sure if the second and third checkboxes are relevant. If deemed needed I can look at doing something

Otherwise my goal with this PR is to be able to pass in shared references that we define. They are supported by the provider as described in their documentation [here](https://github.com/ThomasAribart/json-schema-to-ts#references). All I need was the ability to pass through my references, which accomplished by adding the generic.

### CODE REVIEW

**Comment by kormang** [comment]
Just wanted to make the same thing. Please, merge this. This is game changer, if you want to use Date throughout the code, and serialize/deserialize it to/from string.

I've already tried your code and it works.

**Comment by JeffersonBledsoe** [comment]
Just came to +1 this!

**Review by climba03003 — CHANGES_REQUESTED** [review]
Can you add an unit test on how the new option should behave?
And assert the correct output when you use it.

**Comment by kalvenschraut** [comment]
Didn't realize I was working off the main branch for this, sync'ed up with this repo and added docs and tests for specifically #25 as that was what my use case was also.

**Review by climba03003 — APPROVED** [review]

**Review by RafaelGSS — APPROVED** [review]

**Comment by RafaelGSS** [comment]
Thanks!

**Comment by kalvenschraut** [comment]
Any plans on doing a release soon? Would definitely prefer to track the main package again instead of my fork.

**Pull request merged**
