### PR TITLE
Update for v5

### PR DESCRIPTION
**Pull request by gurgunday**

### CODE REVIEW

**Comment by gurgunday** [comment]
I think the issue is typescript

**Comment by gurgunday** [comment]
@climba03003 I need your help again... 😄

Any idea why windows alone could be failing? Seems like a path/glob issue but not sure where it might be stemming from

**Comment by simoneb** [comment]
@gurgunday although the documentation says that it does, from what I've seen tsc doesn't support globs on the CLI, at least on Windows.

**Comment by gurgunday** [comment]
Thanks so much @simoneb, you saved me a good deal of time there 😄

**Review by Fdawgs — APPROVED** [review]

**Pull request merged**
